
return {
    none          = "none",
    white         = "#FFFFFF",
    one_bg2       = "#282A36",
    normal_darker = "#101217",
    darker_bg     = "#1E2029",
    dark_bg       = "#1F262E",
    purple        = "#BD93F9",
    green         = "#7BE49F",
    str_green     = "#98C379",
    dark_green    = "#8FBCBB",
    blue          = "#81A1C1",
    yellow        = "#EBCB8B",
    lyellow       = "#F1FA8C",
    lred          = "#FFD7D7",
    red           = "#FF6E6E",
    grey          = "#6272A4",
    grey_fg       = "#F8F8F2",
}
